[package]
name = "taika"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# winit = {version = "0.29.14", features = ["x11", "rwh_06"], default-features = false}
winit = "0.30.4"
wgpu = {version = "22.1.0"}
tokio = {version = "1", features = ["full"]}
bytemuck = {version = "1.16.1", features = ["derive"]}
rand = "0.8.5"
async-trait = "0.1"
