[package]
name = "taika"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29.10"
wgpu = {version = "0.19.1", features = ["spirv"]}
tokio = {version = "1.36", features = ["full"]}
