[package]
name = "taika"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# winit = {version = "0.29.14", features = ["x11", "rwh_06"], default-features = false}
winit = "0.29.14"
wgpu = {version = "0.19.3"}
tokio = {version = "1.36", features = ["full"]}
bytemuck = {version = "1.14.3", features = ["derive"]}
